@startuml

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

class ServiceManagerNative{
}
class ServiceManagerProxy{
    IBinder mRemote
}
class ServiceManager {
    IServiceManager sServiceManager
}
ServiceManager -up-> IServiceManager

class Binder{
}

class IBinder {
}

interface IInterface

interface IServiceManager {
    IBinder getService(String name)
    void addService(String name, IBinder service)
}

ServiceManagerNative -up-|> Binder
Binder .u.|> IBinder

ServiceManagerNative .up.|> IServiceManager
ServiceManagerProxy .up.|> IServiceManager
IServiceManager -up-|> IInterface

@enduml