@startuml
title
<font color=red size=16>ProcessState初始化</font>

end title

header
<font color=red>Warning:</font>
Do not use for commercial purposes.
end header
'---------------------------------------------------
participant AppRuntime as AR
participant ProcessState as PS
participant IPCThreadState as ITS
box kernel
participant binder.c as kb order 15
end box

[-->AR:onZygoteInit
note over AR
应用进程启动的时候都会
通过Zygote调用到这里
end note
activate AR
AR->PS:self
activate PS
PS->PS:<单例模式>\n//<color red>gProcess//
PS->PS:new ProcessState
activate PS
note over PS
ProcessState初始化,如下：
mDriverName="/dev/binder" binder驱动名字
mDriverFD binder设备描述符
mVMStart 虚拟内存空间映射起始地址
mMaxThreads=15 默认最大线程数
end note
PS->PS:open_driver
activate PS
PS-->kb:open
PS-->kb:ioctl\n//获取binder版本
PS-->kb:ioctl\n//设置最大线程
deactivate PS
PS-->kb:mVMStart=mmap
note over PS
映射一块虚拟地址空间用来接收transactions
BINDER_VM_SIZE:大小为1M-2pages
PROT_READ:只读
end note
deactivate PS
return gProcess

AR->PS:startThreadPool
deactivate AR
activate PS
PS->PS:spawnPooledThread(\n//<color red>isMain=true//)
activate PS
PS->PS:makeBinderThreadName
hnote over PS
构建binder线程name,结构为"Binder:pid_x"
例如：Binder:10018_1,x为递增配置的
通过命令ps -A -T|grep Binder可以看到
end hnote
PS->PS:new PoolThread()->run()
deactivate PS
return

PS o-> PS:PoolThread.threadLoop
activate PS
PS->ITS:self
activate ITS
ITS->ITS:new IPCThreadState
return
deactivate ITS
PS->ITS:joinThreadPool(\n//<color red>mIsMain=true//)
deactivate PS
activate ITS
activate ITS
ITS->ITS:mOut.write(\nBC_ENTER_LOOPER)
hnote over ITS:BC_ENTER_LOOPER用来告诉kernel当前线\n程进入Looper,可以开始工作
create control threadpool
ITS->threadpool:while(true)
deactivate ITS
participant threadpool order 12
activate threadpool
threadpool->threadpool:getAndExecuteCommand
activate threadpool
threadpool->threadpool:talkWithDriver
activate threadpool
threadpool->threadpool:bwr.write_buffer=mOut.data()
threadpool->kb:ioctl(BINDER_WRITE_READ,&bwr)
deactivate threadpool
deactivate threadpool

hnote over threadpool:循环读取mOut数据并发给kernel


'---------------------------------------------------
right footer Generated by Yaoguang
@enduml