@startuml
title
<font color=red size=16>View类图</font>

endtitle

header
<font color=red>Warning:</font>
Do not use for commercial purposes.
endheader
'-----------------------------------------------------------
interface ViewParent {
}
class ViewRootImpl {
    final Surface mSurface
    View.AttachInfo mAttachInfo
    final IWindowSession mWindowSession;
}
ViewRootImpl .up.|> ViewParent
ViewRootImpl .up.|> Callbacks
ViewRootImpl .up.|> DrawCallbacks
'#############################
class View {
    RenderNode mRenderNode
}
class AttachInfo {
    final ViewRootImpl mViewRootImpl
    ThreadedRenderer mThreadedRenderer
    IWindowSession mSession
}
interface Callbacks {
}
View +-- AttachInfo
AttachInfo +-- Callbacks
'#############################
class ThreadedRenderer {
}
class HardwareRenderer {
}
interface DrawCallbacks {
}

ThreadedRenderer -up-|> HardwareRenderer
ThreadedRenderer +-- DrawCallbacks
'#############################
interface WindowManager {
}
WindowManager .up.|> ViewManager
interface ViewManager {
    void addView(View view, ViewGroup.LayoutParams params)
}
class WindowManagerImpl {
    final WindowManagerGlobal mGlobal
}
WindowManagerImpl --> WindowManagerGlobal
WindowManagerImpl .up.|> WindowManager
class WindowManagerGlobal {
    final ArrayList<View> mViews
    final ArrayList<ViewRootImpl> mRoots
    final ArrayList<WindowManager.LayoutParams> mParams
    void addView(View view, ViewGroup.LayoutParams params, ...)
}
note bottom of WindowManagerGlobal
mViews,mRoots,mParams分别记录WMG管理的
view以及其对应的ViewRootImpl和Params，
三个List同增同减，也就是说相同index对应的
就是同一个View的相关信息
end note
WindowManagerGlobal -up-> ViewRootImpl
note "Activity.makeVisible();Dialog.show;等给\n新window添加View的时候会调用addView" as note1
note1 .right. WindowManager
'-----------------------------------------------------------
right footer Generated by Yaoguang
@enduml